export type CatType =
  | "siamese"
  | "persian"
  | "maine_coon"
  | "british_shorthair"
  | "ragdoll"
  | "bengal"
  | "sphynx"
  | "scottish_fold"
  | "abyssinian"
  | "american_shorthair"
  | "orange"
  | "black"
  | "gray"
  | "calico";
